loop: v0.8.1 -> v0.9.0
fort-nix/nix-bitcoin pull request #234
Opened 2020-09-15 12:21 UTC by nixbitcoin

This PR updates the loop pkg. It also updates the module package to fully utilize the changes introduced in v0.9.0.

When we release this we need to include instructions, ideally a one-line command, to migrate existing loop directories from `/var/lib/lnd/.loop/ to `/var/lib/lightning-loop`.

2020-09-22 13:46 UTC, jonasnick approved these changes
ACK 56705fbd16c98e2b9f3f1098a6c994f19a97f47b

2020-09-23 14:04 UTC, erikarvstedt requested changes
[Fixups.](https://github.com/erikarvstedt/nix-bitcoin/commits/loop-0.9.0-ea)

2020-09-23 14:18 UTC, erikarvstedt commented on modules/lightning-loop.nix
> +        WorkingDirectory = cfg.dataDir;
After a bit of testing it seems `WorkingDirectory` isn't used.

2020-09-24 17:07 UTC, nixbitcoin commented
Rebased, squashed your fixups and removed `WorkingDirectory`

2020-09-24 17:34 UTC, erikarvstedt approved these changes
ACK.
We should merge [BTCPayServer from upstream & postgresqlBackup](https://github.com/fort-nix/nix-bitcoin/pull/237) first

2020-09-25 18:00 UTC, jonasnick commented
reACK 56705fbd16c98e2b9f3f1098a6c994f19a97f47b

2020-09-25 18:03 UTC, erikarvstedt commented
Commit `test: increase diskSize` was included in 73f4275d2a2bdef34644aabbefa43ae748fd6d6f and can be removed.

2020-09-25 18:06 UTC, erikarvstedt commented
ACK a89a3e934f485bd9b0c159e18f6af91883c56e84

2020-09-25 21:21 UTC, jonasnick commented
> Commit `test: increase diskSize` was included in 73f4275d2a2bdef34644aabbefa43ae748fd6d6f and can be removed. 

@erikarvstedt That's what I was thinking too immediately after I acked again, but you apparently removed this comment, why?

2020-09-25 21:46 UTC, erikarvstedt commented
Yeah, removing the commit improves the git history, but it doesn't affect the final code.
I'd have preferred to just get done with this PR. :wink:
I think it's okay if you would just merge 24b506ff8a2c2d788e102548423cb75bfe4d81e4, which is the direct parent of the ACK'd a89a3e934f485bd9b0c159e18f6af91883c56e84, and removing a89a3e934f485bd9b0c159e18f6af91883c56e84 itself is totally uncontroversial.

ACK https://github.com/fort-nix/nix-bitcoin/commit/24b506ff8a2c2d788e102548423cb75bfe4d81e4

2020-09-29 17:50 UTC, merged

2020-09-29 17:58 UTC, jonasnick commented
For posteriority I merged a89a3e934f485bd9b0c159e18f6af91883c56e84 because it wasn't straightforward to remove within my merge script.