joinmarket: 0.7.4 -> bcfa7eb
fort-nix/nix-bitcoin pull request #283
Opened 2020-12-14 17:40 UTC by nixbitcoin

This PR updates JoinMarket to 0.8.0 plus a hotfix for the genwallet script that I wrote myself. It includes a warning about the necessary migration steps. This warning isn't something for config versioning, right?

I had to temporarily change `get-sha256.sh` for the pinned commit. We can revert all this with version 0.8.1.

2020-12-14 18:43 UTC, erikarvstedt commented
This is a perfect use case for config versioning, because this warning is only relevant for users of the previous version of the joinmarket module.

Here's a draft [here](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.8.0-ea).

Could you add a bit more detail about step `jm-wallet-tool bak.jmdat`?
Or is this really all that's necessary to transfer the funds to the new wallet?

2020-12-15 11:55 UTC, nixbitcoin commented
I squashed your commit and included thorough migrations steps.

I also had to point out that in this case, we first have to change the `configVersion` and deploy, then perform the migration steps. Any smarter way to do this?

2020-12-15 21:55 UTC, erikarvstedt commented
> Any smarter way to do this?

No, it's fine this way.

[Fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.8.0-ea)

2020-12-16 09:13 UTC, nixbitcoin commented
Doing `cd ${dataDir}/wallets` is actually not necessary because we do `cd '${cfg.dataDir}' && ${cfg.cliExec} sudo -u ${cfg.user} $jm/$bin --datadir='${cfg.dataDir}` on every command.

Also I think you meant to say `0: set amount to zero to do a sweep, i.e. transfer all funds at given mixdepth` not `0: set amount to zero to do a sweep, i.e. transfer all funds at given`

2020-12-16 14:39 UTC, erikarvstedt requested changes
We should also note that different destination addresses should be used for each sweep.

2020-12-16 14:39 UTC, erikarvstedt commented on modules/versioning.nix
> +           You might want to time stagger these 4 transactions.
```suggestion
           You might want to time stagger these transactions.
```
The number of max. mixdepths is configurable and the default is 5 (= 5 transactions).

2020-12-16 14:39 UTC, erikarvstedt commented on modules/versioning.nix
> +           -N 0: don't coinjoin on this spend
Doesn't this decrease privacy because all input transactions can be linked together?

2020-12-16 15:39 UTC, nixbitcoin commented
> We should also note that different destination addresses should be used for each sweep.

Done. Also included possibility of coin-freezing to use individual coins and not connect them

2020-12-16 19:00 UTC, erikarvstedt commented
[Final fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.8.0-ea).

2020-12-17 11:14 UTC, nixbitcoin commented
> [Final fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.8.0-ea).

Squashed

2020-12-17 12:07 UTC, erikarvstedt approved these changes
ACK fdfafb2f40076ed053ccac288c2d33ffb117e313

2020-12-20 19:31 UTC, merged

2020-12-20 19:32 UTC, jonasnick commented
Man, that config versioning stuff really is super cool.