WIP: BTCPayServer L-BTC Support
fort-nix/nix-bitcoin pull request #369
Opened 2021-07-13 15:17 UTC by nixbitcoin

Excuse the hackyness of pulling in a custom `nixpkgs-unstable` for the BTCPayServer Altcoin support. I'm working on patching it elegantly upstream.

2021-07-14 10:23 UTC, prusnak commented on pkgs/nixpkgs-pinned.nix
> +    url = "https://github.com/nixbitcoin/nixpkgs/archive/e8135bdc7f26125e072186c66ae0c27fe35ffdae.tar.gz";
Please send a PR to nixpkgs with this change (https://github.com/nixbitcoin/nixpkgs/commit/e8135bdc7f26125e072186c66ae0c27fe35ffdae) and ping me in the PR

2021-07-14 12:55 UTC, prusnak commented
Is it possible to patch BtcPayServer in a way the build allows L-BTC but does not allow Ethereum?

2021-07-15 09:12 UTC, nixbitcoin commented
> Is it possible to patch BtcPayServer in a way the build allows L-BTC but does not allow Ethereum?

I asked the same question originally in the BTCPayServer chat. The answer was no. Can you confirm this @kukks?

2021-07-15 10:08 UTC, Kukks commented
> > Is it possible to patch BtcPayServer in a way the build allows L-BTC but does not allow Ethereum?
> 
> I asked the same question originally in the BTCPayServer chat. The answer was no. Can you confirm this @Kukks?

I can confirm. We only have 1 compile time flag for anything that expands beyond a "BTC" currency code

2021-07-20 22:06 UTC, prusnak requested changes

2021-07-20 22:06 UTC, prusnak commented on pkgs/nixpkgs-pinned.nix
> +    sha256 = "05irab32svmfsdlfy1810m6q36fdk2kfh7ipm9ir85csic5rvcjq";
https://github.com/NixOS/nixpkgs/pull/130162 has been merged, so this change can be dropped.

2021-07-21 12:55 UTC, nixbitcoin commented
Need to wait until it's in nixos-unstable

2021-08-09 10:02 UTC, nixbitcoin commented
Ready for review/merge

2021-08-09 11:06 UTC, erikarvstedt commented
Beautiful implementation.
[Some minor fixups](https://github.com/erikarvstedt/nix-bitcoin/commits/btcpayserver-liquid-ea).

2021-08-10 10:12 UTC, nixbitcoin commented
Squashed fixups, ready for merge

2021-08-10 10:54 UTC, erikarvstedt approved these changes
ACK 54810ce1bfeb275e4a2f875c2a57b81d36dc054d

2021-08-10 12:22 UTC, merged