clightning-plugins: add commando plugin
fort-nix/nix-bitcoin pull request #445
Opened 2022-01-22 21:18 UTC by jb55

2022-01-22 21:25 UTC, jb55 commented
currently using [a patch](https://github.com/jb55/runes/commit/1e24c0898bdf979a47ce0cfb24792fe24ae4e98a) on top of @rustyrussell's [rune](https://github.com/rustyrussell/rune). I've emailed him the patch, so will switch back to his repo once it's applied.

2022-01-23 19:26 UTC, jonasnick reviewed
Thank you for the PR @jb55. Can you help me understanding what the use case of commando is? By the way, we should add the plugin to the tests as well (see `services.clightning.plugins` in `tests.nix`)

2022-01-24 15:00 UTC, jb55 commented
commando allows you to perform clightning RPC over the lightning network itself. I built [lnsocket](http://git.jb55.com/lnsocket), a C library that can talk the lightning network and send/receive commando packets, so that I could build an iOS app that controls my lightning node without having to run wireguard, spark, etc.

2022-01-29 15:56 UTC, jb55 commented
>By the way, we should add the plugin to the tests as well (see `services.clightning.plugins` in `tests.nix`)

Is this all I have to do ?

https://github.com/fort-nix/nix-bitcoin/pull/445/commits/d5f0906cf13de48c96f43246b4426ddf9de396ab

2022-02-05 21:17 UTC, jonasnick commented
Oh sorry! The tests only test modules and I just noticed taht this PR doesn't add a module for commando.

2022-02-06 18:03 UTC, jb55 commented
On Sat, Feb 05, 2022 at 01:17:53PM -0800, Jonas Nick wrote:
>Oh sorry! The tests only test modules and I just noticed taht this PR doesn't add a module for commando.

ok I removed that commit

2022-02-08 15:13 UTC, nixbitcoin commented
[Minor Fixups](https://github.com/nixbitcoin/nix-bitcoin/commits/commando-plugin-nb)

I built the `commando` package locally and tested importing it in lightningd on a nix-bitcoin VM with

```
lightning-cli plugin start /nix/store/r9irz59nb9g9fpg5j45q8014014miq8z-clightning-plugin-commando-b88c927/commando.py
lightning-cli commando-rune restrictions=readonly
```

2022-02-21 03:55 UTC, jb55 commented
On Tue, Feb 08, 2022 at 07:13:44AM -0800, nixbitcoindev wrote:
>[Minor Fixups](https://github.com/nixbitcoin/nix-bitcoin/commits/commando-plugin-nb)

I've split my commits and integrated these fixups

2022-02-21 13:07 UTC, nixbitcoin commented on pkgs/python-packages/runes/default.nix
> +    homepage = "https://github.com/rustyrussel/runes";
ACK mod nit

s/rustyrussel/rustyrussell

I would prefer to merge this with a module, but it's ok to merge without for now from my side.

2022-02-21 18:46 UTC, jb55 commented
On Mon, Feb 21, 2022 at 05:08:09AM -0800, nixbitcoindev wrote:
>ACK mod nit
>
>s/rustyrussel/rustyrussell

done

2022-02-22 13:53 UTC, nixbitcoin submitted a review, later dismissed
ACK cd15202cb106274436f2b3767e60bae36319edee

2022-02-23 19:36 UTC, erikarvstedt commented
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/commando-plugin-ea).
- Add `commando` module
- Add `python-packages` prefix to commit titles

2022-02-24 00:21 UTC, jb55 commented
On Wed, Feb 23, 2022 at 11:36:11AM -0800, erikarvstedt wrote:
>[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/commando-plugin-ea).
>- Add `commando` module
>- Add `python-packages` prefix to commit titles

range diff LGTM, forced pushed to your branch

2022-02-24 09:48 UTC, erikarvstedt commented
I forgot to update the README, [Fixed here](https://github.com/erikarvstedt/nix-bitcoin/tree/commando-plugin-ea/).

2022-02-24 16:34 UTC, jb55 commented
@erikarvstedt done!

2022-02-24 17:40 UTC, erikarvstedt approved these changes
ACK 2d6c4e829e655260dd4f33f2dae85ae1e8090ed7

2022-02-26 18:11 UTC, jb55 commented
@erikarvstedt sorry to invalidate your ACK but I pushed 7530f5980687d22591984ea8cf231c1447a708e7 since the pycparser version constraint was a bit hostile to newer nixpkgs versions.

2022-02-27 13:16 UTC, erikarvstedt requested changes

2022-02-27 13:16 UTC, erikarvstedt commented on pkgs/python-packages/pyln-proto/default.nix
> +      s|pycparser==2.20|pycparser>=2.20|
```suggestion
      s|pycparser==2.20|pycparser~=2.20|
```
This is safer because it rejects potentially incompatible major version updates.

2022-02-27 17:58 UTC, erikarvstedt approved these changes
ACK ee4cdb0586117125fd1a2c2329655aeedd601da7

2022-02-27 18:36 UTC, jonasnick reviewed
Concept ACK

2022-02-27 18:37 UTC, merged