ShellCheck for various helper bash scripts
fort-nix/nix-bitcoin pull request #531
Opened 2022-08-04 18:28 UTC by seberm

This PR adds shellcheck lint to helper bash scripts, for more info please see:
- https://github.com/fort-nix/nix-bitcoin/issues/528

2022-08-14 20:13 UTC, jonasnick reviewed
Thanks a lot @seberm, this is very helpful! I skimmed the shellcheck'd code and ran a few of the scripts. Looks good.

2022-08-14 20:13 UTC, jonasnick commented on .cirrus.yml
>          # Use Nix release 2.3.x, the default on NixOS stable
This comment needs to be updated.

2022-08-14 20:13 UTC, jonasnick commented on test/ci/shellcheck.sh
> +# scheck_file "$scriptDir/shellcheck.sh"
Why add this then (including the scheck_file function)

2022-08-14 20:13 UTC, jonasnick commented on test/ci/shellcheck.sh
> +# TODO: add possibility to run this script directly
I think ideally it would be possible to run shellcheck with our `run-tests.sh` script and include it in `all()`.

2022-08-16 19:31 UTC, seberm commented
Hello @jonasnick ,
thank you for your review! I've made the suggested changes and added the shellcheck into the `run-tests.sh`. Let me know if everything works as expected.

2022-08-25 10:09 UTC, seberm commented
Hello @jonasnick ,
I have rebased the changes against the current master.

2022-08-25 14:10 UTC, jonasnick reviewed
Thanks @seberm. ACK mod nits. I want to merge this PR asap to avoid having to rebase it all the time. @erikarvstedt can you Concept ACK this?

2022-08-25 14:10 UTC, jonasnick commented on test/ci/shellcheck.sh
> +    popd
nit: can you redirect the output of `pushd` and `popd` to `/dev/null`? This makes the output of `shellcheck.sh` much more comprehensible.

2022-08-25 14:10 UTC, jonasnick commented on test/run-tests.sh
> +}
nit: Doesn't it make more sense to have shellcheck.sh in the `tests/` directory?

2022-08-26 06:49 UTC, jonasnick submitted a review, later dismissed
ACK c4e78281985aa53fec067ed778979aace956206e

2022-08-27 12:05 UTC, erikarvstedt requested changes
Amazing, thanks a lot!

[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/feature/shellcheck-for-helper-scripts-ea).

- Fix `start-bash-session.sh` which was broken due to shellcheck comments inserted into a
multi-line command.
- `run-tests.sh`: Fix rounding down of `memAvailableKiB`
- `run-tests.sh`: Add shellcheck binary to PATH for test `shellcheck`
- `shellcheck.sh`: Simplify, find all scripts in repo
- `.cirrus.yml`: Improve usage of the root flake
- `.cirrus.yml`: Use the actual Nix version from NixOS 22.05
- `.cirrus.yml`: Simplify test `shellcheck`

2022-08-28 15:02 UTC, erikarvstedt commented
[Fixed branch](https://github.com/erikarvstedt/nix-bitcoin/commits/feature/shellcheck-for-helper-scripts-ea-2).

Thanks for fixing `fetch-release`.
Instead of renaming the file, I've now modified that test script to include files without extensions that have a
shell shebang.

2022-08-28 15:20 UTC, seberm commented
Hello Erik,
you were quick :) !, thanks a lot for your review and the changes!

Hopefully I have rebased everything correctly :). Let me know if anything more is needed.

2022-08-28 15:39 UTC, erikarvstedt approved these changes
ACK 1a0df13d6c56d2120ecdb2027fc45c435f889cd4

2022-08-28 16:09 UTC, erikarvstedt requested changes
Sorry, last fix: I've updated my branch above to pin shellcheck (and other binaries) used in the CI script to our version of nixpkgs.

2022-08-28 16:17 UTC, seberm commented
> Sorry, last fix: I've updated my branch above to pin shellcheck (and other binaries) used in the CI script to our version of nixpkgs.

No problem.

2022-08-28 16:28 UTC, erikarvstedt approved these changes
ACK 91a03ce7d2a4d92edcb875938454da91b4178a21

2022-08-28 17:22 UTC, jonasnick reviewed
ACK 91a03ce7d2a4d92edcb875938454da91b4178a21

Thanks @seberm @erikarvstedt !

2022-08-28 17:23 UTC, merged