clboss: 0.13 -> 0.14-pre
fort-nix/nix-bitcoin pull request #694
Opened 2024-05-05 15:14 UTC by erikarvstedt

Opening new channels, the main feature of clboss, was broken with clightning v24.02:
https://github.com/ZmnSCPxj/clboss/issues/189

2024-05-05 15:25 UTC, prusnak requested changes
rev `2c7ce2f5b905d1eb3a5298404ad669f4463511b2` has been tagged as https://github.com/ZmnSCPxj/clboss/releases/tag/v0.13.1

2024-05-05 15:25 UTC, prusnak commented on pkgs/clboss/default.nix
> +  version = "0.14-pre";
```suggestion
  version = "0.13.1";
```

2024-05-05 15:25 UTC, prusnak commented on pkgs/clboss/default.nix
> +    rev = "2c7ce2f5b905d1eb3a5298404ad669f4463511b2";
```suggestion
    rev = "v${version}";
```

2024-05-05 15:28 UTC, erikarvstedt commented on pkgs/clboss/default.nix
> +    rev = "2c7ce2f5b905d1eb3a5298404ad669f4463511b2";
Great, thank you!

2024-05-05 15:51 UTC, prusnak approved these changes

2024-05-06 07:03 UTC, jonasnick approved these changes
utACK eafcb361192641730d7a9ef9466c77a19f0eeb63

2024-05-06 07:10 UTC, merged

2024-05-08 08:14 UTC, prusnak commented
Btw clboss 0.13.1 is now in nixpkgs, maybe we can use the package from there?

https://github.com/NixOS/nixpkgs/pull/310007